# baseURL = "http://sls-comps.example.com/"
languageCode = "en-us"
title = "Pulum Anda Real Estate Blog"
theme = "bleak"
#publishDir = "<target_publish_folder>"

[params]
  Subtitle = "easy, composable, open, serverless components"
  cover = "/images/serverless-components.gif"