# baseURL = "http://sls-comps.example.com/"
languageCode = "en-us"
title = "Pulum Anda Real Estate Blog"
theme = "bleak"
publishDir = "public"

[params]
  Subtitle = "realestate,commercial,residential,bedsitters,standalone house,spacious units"
  cover = "/images/serverless-components.gif"

