# baseURL = "http://sls-comps.example.com/"
languageCode = "en-us"
title = "Napitalai ICT Blog"
theme = "bleak"
#publishDir = "public"

[params]
  Subtitle = "web designing and programming,servers,networking,ethical hacking,web applications,web mapping,html,css,scripting"
  cover = "images/tn.png"

