[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.40.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.40.3"
  command = "npm run build-preview"