backend:
  name: git-gateway
  #branch : step-01-add-a-menu
  repo: anapitalai/staticmaninuse # Path to Github repository
  #branch: master
  publish_mode: editorial_workflow


media_folder: "images"
public_folder: "/images"


collections:
  - name: gallery
    label: "Gallery Image" # Used in the UI, ie.: "New Post"
    folder: "content/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Gallery Image", name: "image", widget: "image"}

  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", optional: false}

